// BDL_TREE_SPECIES_INFO.js — auto-generated by generate_bdl_data.js
// Run:  node generate_bdl_data.js   to populate with real BDL data.
// Format: [lat, lng, species_cd, age_years]
// species_cd = BDL codes: SO=pine  BRZ=birch  DB=oak  BK=beech  SW=spruce  MD=larch  OL=alder  GB=hornbeam
const BDL_TREE_SPECIES_INFO=[];
