// generate_bdl_data.js — builds BDL_TREE_SPECIES_INFO.js
// Queries BDL at 0.01° grid (≈700m) across the GrzyboMapa coverage area
// and saves real species codes for every forest stand hit.
//
// Usage:  node generate_bdl_data.js
// Requires Node.js 18+ (native fetch).
// Takes ~3–5 minutes. Re-run whenever you want fresher data.

const LAT_MIN = 52.50, LAT_MAX = 53.85;
const LNG_MIN = 16.50, LNG_MAX = 18.25;
const STEP    = 0.01;   // ~700 m lat / ~600 m lng at 53°N
const CONCURRENCY = 20; // parallel requests — be polite to BDL server
const OUT_FILE = 'BDL_TREE_SPECIES_INFO.js';
const RETRY    = 2;     // retries per failed request

const BDL_WMS = 'https://mapserver.bdl.lasy.gov.pl/arcgis/services/WMS_BDL_mapa_drzewostanow/MapServer/WMSServer';

async function queryBDL(lat, lng, tries = 0) {
  const span = 0.006;
  const bbox = `${lat - span},${lng - span * 1.5},${lat + span},${lng + span * 1.5}`;
  const url  = `${BDL_WMS}?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo` +
    `&BBOX=${bbox}&CRS=EPSG:4326&WIDTH=100&HEIGHT=100` +
    `&LAYERS=0,1,2,3,4,5&STYLES=&FORMAT=image%2Fpng` +
    `&QUERY_LAYERS=0,1,2,3,4,5&I=50&J=50&INFO_FORMAT=application%2Fgeo%2Bjson`;
  try {
    const d = await fetch(url, { signal: AbortSignal.timeout(8000) }).then(r => r.json());
    const f = (d.features || []).find(ft => {
      const v = ft.properties?.species_cd;
      return v && v !== 'Null' && v !== '-';
    }) || d.features?.[0];
    const p   = f?.properties || {};
    const cl  = v => (v === 'Null' || v == null) ? '' : String(v).trim();
    const cd  = cl(p.species_cd);
    const age = parseInt(cl(p.species_age)) || 0;
    return cd ? { lat, lng, cd, age } : null;
  } catch (e) {
    if (tries < RETRY) return queryBDL(lat, lng, tries + 1);
    return null;
  }
}

async function main() {
  // Generate grid points
  const pts = [];
  for (let la = LAT_MIN; la <= LAT_MAX + 1e-9; la = +(la + STEP).toFixed(4))
    for (let lo = LNG_MIN; lo <= LNG_MAX + 1e-9; lo = +(lo + STEP).toFixed(4))
      pts.push([la, lo]);

  console.log(`Grid: ${pts.length} points over ${LAT_MIN}–${LAT_MAX}°N, ${LNG_MIN}–${LNG_MAX}°E`);
  console.log(`Concurrency: ${CONCURRENCY}. Estimated time: ${Math.ceil(pts.length / CONCURRENCY * 0.3 / 60)} min`);

  const results = [];
  let done = 0;

  for (let i = 0; i < pts.length; i += CONCURRENCY) {
    const batch = pts.slice(i, i + CONCURRENCY);
    const res   = await Promise.all(batch.map(([la, lo]) => queryBDL(la, lo)));
    res.forEach(r => { if (r) results.push(r); });
    done += batch.length;
    const pct = (done / pts.length * 100).toFixed(1);
    process.stdout.write(`\r  ${done}/${pts.length} (${pct}%) — ${results.length} forest stands found`);
  }
  console.log('\n');

  // Sort by lat then lng for deterministic output
  results.sort((a, b) => a.lat - b.lat || a.lng - b.lng);

  const rows = results.map(r =>
    `[${r.lat.toFixed(4)},${r.lng.toFixed(4)},'${r.cd}',${r.age}]`
  ).join(',\n');

  const header = [
    '// BDL_TREE_SPECIES_INFO.js — auto-generated by generate_bdl_data.js',
    `// Coverage: ${LAT_MIN}–${LAT_MAX}°N, ${LNG_MIN}–${LNG_MAX}°E`,
    `// ${results.length} forest stands · grid step ${STEP}°`,
    `// Generated: ${new Date().toISOString().slice(0, 10)}`,
    '// Format: [lat, lng, species_cd, age_years]',
    '// species_cd = BDL codes: SO=pine  BRZ=birch  DB=oak  BK=beech  SW=spruce  MD=larch  OL=alder  GB=hornbeam  etc.',
    '// Multiple codes joined by "." e.g. "SO.BRZ" = pine+birch mixed stand',
    `const BDL_TREE_SPECIES_INFO=[`,
  ].join('\n');

  require('fs').writeFileSync(OUT_FILE, `${header}\n${rows}\n];\n`, 'utf8');

  const kb = (require('fs').statSync(OUT_FILE).size / 1024).toFixed(0);
  console.log(`Written ${OUT_FILE} (${kb} KB, ${results.length} stands)`);
}

main().catch(err => { console.error(err); process.exit(1); });
